"""Dynamic Entrys

Revision ID: 1d876b543986
Revises: 
Create Date: 2022-05-10 13:53:44.945261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d876b543986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dynamic_entry')
    # ### end Alembic commands ###
